name: skystudy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0 # Phiên bản SDK tương thích với các package hiện tại

dependencies:
  flutter:
    sdk: flutter
  # State management và điều hướng
  get: ^4.6.5
  # HTTP client để gọi API
  dio: ^5.8.0
  # Logging framework để thay thế print
  logger: ^2.5.0
  # Hỗ trợ animation Lottie
  lottie: ^3.3.1
  # Lưu trữ dữ liệu cục bộ (ví dụ: lưu token sau khi đăng nhập)
  get_storage: ^2.1.1
  # Cupertino Icons cho iOS style icons
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lint rules để đảm bảo code chất lượng
  flutter_lints: ^5.0.0
  # (Tùy chọn) Thêm mockito nếu bạn muốn viết unit test
  # mockito: ^5.4.4

flutter:
  # Đảm bảo Material Icons font được bao gồm
  uses-material-design: true

  # Khai báo assets
  # Chỉ cần khai báo thư mục gốc, các thư mục con sẽ tự động được bao gồm
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/lottie/