name: skystudy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0 # Phiên bản SDK tương thích với các package hiện tại

dependencies:
  flutter:
    sdk: flutter
  # tflite_flutter: ^0.11.0
  flutter_tts: ^4.2.2
  path: ^1.8.0 # Thư viện path để xử lý đường dẫn file
  ultralytics_yolo: 0.0.3
  async: ^2.11.0
  camera: ^0.11.1 
  permission_handler: ^11.0.1
  path_provider: ^2.0.11
  shared_preferences: ^2.5.3
  dio: ^5.0.0
  logger: ^2.0.0
  get: ^4.7.2
  image: ^4.0.11
  lottie: ^3.3.1
  get_storage: ^2.1.1
  web_socket_channel: ^3.0.2
  http_parser : ^4.0.2
  http : ^1.2.2
  audioplayers: ^5.2.1
  flutter_sound: ^9.2.13
  google_fonts: ^6.2.1
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  speech_to_text: ^7.0.0
  just_audio: ^0.10.0
  flutter_slidable: ^4.0.0
  yaml: ^3.1.2
  flutter_dotenv: ^ 5.2.1
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lint rules để đảm bảo code chất lượng
  flutter_lints: ^5.0.0
  # (Tùy chọn) Thêm mockito nếu bạn muốn viết unit test
  # mockito: ^5.4.4

flutter:
  # Đảm bảo Material Icons font được bao gồm
  uses-material-design: true

  # Khai báo assets
  # Chỉ cần khai báo thư mục gốc, các thư mục con sẽ tự động được bao gồm
  assets:
    - .env
    - assets/
    - assets/avatar/
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/lottie/
    - assets/labels.txt
    - assets/efficientdet_lite0.tflite
    - assets/yolov8n_int8.tflite
    - assets/yolov8n_float16.tflite
    - assets/yolov8n_float32.tflite
    - assets/yolo11n_float16.tflite
    - assets/yolo11n_int8.tflite
    - assets/metadata.yaml